export enum ResearchStep {
    welcome = 'Welcome',
    firstQuestion = 'FirstQuestion',
    secondQuestion = 'SecondQuestion',
    thirdQuestion = 'ThirdQuestion',
    fourthQuestion = 'FourthQuestion',
    questionCampusAround = 'QuestionCampusAround',
    answerCampusAround = 'AnswerCampusAround',
    informationPayment = 'InformationPayment',
    informationPerformance = 'InformationPerformance',
    questionPerformanceAndPayment = 'QuestionPerformanceAndPayment',
    answerPerformanceAndPayment = 'AnswerPerformanceAndPayment',
    goToExplorer = 'GoToExplorer',
    paymentQuestion = 'PaymentQuestion',
    PerformanceQuestion = 'PerformanceQuestion',
}
